In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
M= np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]])

In [5]:
M

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]])

In [6]:
type(M)

numpy.ndarray

In [7]:
M.dtype

dtype('int32')

In [8]:
M

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]])

In [9]:
M= np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype = np.int8)
M

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [10]:
#order of matrix
M.shape

(4, 3)

In [11]:
M.size

12

In [12]:
M.ndim

2

In [13]:
M[0]

array([5, 4, 3], dtype=int8)

In [14]:
M[1]

array([1, 7, 8], dtype=int8)

In [15]:
M[1][2]

8

In [16]:
M[1,2]

8

In [17]:
M[1,2] = 56

In [18]:
M

array([[ 5,  4,  3],
       [ 1,  7, 56],
       [ 0,  2,  3],
       [ 7,  5,  1]], dtype=int8)

In [19]:
print(M)

[[ 5  4  3]
 [ 1  7 56]
 [ 0  2  3]
 [ 7  5  1]]


In [20]:
M.reshape(3,4)

array([[ 5,  4,  3,  1],
       [ 7, 56,  0,  2],
       [ 3,  7,  5,  1]], dtype=int8)

In [21]:
M.reshape(6,2)

array([[ 5,  4],
       [ 3,  1],
       [ 7, 56],
       [ 0,  2],
       [ 3,  7],
       [ 5,  1]], dtype=int8)

In [22]:
M.reshape(1,12)

array([[ 5,  4,  3,  1,  7, 56,  0,  2,  3,  7,  5,  1]], dtype=int8)

In [23]:
M.reshape(-1,2)

array([[ 5,  4],
       [ 3,  1],
       [ 7, 56],
       [ 0,  2],
       [ 3,  7],
       [ 5,  1]], dtype=int8)

In [24]:
M.reshape(2,-1)

array([[ 5,  4,  3,  1,  7, 56],
       [ 0,  2,  3,  7,  5,  1]], dtype=int8)

In [25]:
M.reshape(-1)

array([ 5,  4,  3,  1,  7, 56,  0,  2,  3,  7,  5,  1], dtype=int8)

In [26]:
M.flatten()

array([ 5,  4,  3,  1,  7, 56,  0,  2,  3,  7,  5,  1], dtype=int8)

In [27]:
v1= np.array([3,4,2,1,6,5,4,7,8])

In [28]:
v1.shape

(9,)

In [29]:
v1.reshape(3,3)

array([[3, 4, 2],
       [1, 6, 5],
       [4, 7, 8]])

In [30]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
M.astype(np.float16)

array([[ 5.,  4.,  3.],
       [ 1.,  7., 56.],
       [ 0.,  2.,  3.],
       [ 7.,  5.,  1.]], dtype=float16)

In [32]:
M.astype(np.bool_)

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [33]:
M.astype(np.unicode_)

array([['5', '4', '3'],
       ['1', '7', '56'],
       ['0', '2', '3'],
       ['7', '5', '1']], dtype='<U4')

In [34]:
for i in range(4):
    for j in range(3):
        print(M[i][j], end=' ')
    print()

5 4 3 
1 7 56 
0 2 3 
7 5 1 


In [35]:
M.min()

0

In [36]:
M.max()

56

In [37]:
M.mean()

7.833333333333333

In [38]:
M.std()

14.684648068268059

In [39]:
M.var()

215.63888888888883

In [40]:
np.median(M)

3.5

In [41]:
M.sum()

94

In [42]:
Z=np.zeros([3,3], dtype= np.int8)

In [43]:
Z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [44]:
O=np.ones([3,3], dtype= np.int8)
O

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [45]:
S=np.arange(25).reshape(5,5)

In [46]:
S

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
S[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [48]:
S[:3,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [49]:
S[1:3,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [50]:
M>4

array([[ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [51]:
M[M>4]

array([ 5,  7, 56,  7,  5], dtype=int8)

In [52]:
M[M%2 == 0]

array([ 4, 56,  0,  2], dtype=int8)

In [53]:
M[M%2 == 1]

array([5, 3, 1, 7, 3, 7, 5, 1], dtype=int8)

In [54]:
M1 = np.array([[6,8,7],[4,1,3],[5,2,9]])

In [55]:
M1

array([[6, 8, 7],
       [4, 1, 3],
       [5, 2, 9]])

In [56]:
for i in range(M1.shape[0]):
    for j in range(M1.shape[1]):
        if M1[i][j] %2 ==0:
            M1[i][j] = 0

In [57]:
M1

array([[0, 0, 7],
       [0, 1, 3],
       [5, 0, 9]])

<h5>Matrix Operations</h5>

Addition

In [60]:
M1 = np.array([[5,4,3], [1,7,8], [0,2,3],[7,5,1]], dtype = np.int8)
M2 = np.array([[2,8,1], [0,2,5], [1,9,4],[6,2,6]], dtype = np.int8)

In [61]:
M1.shape,M2.shape

((4, 3), (4, 3))

In [62]:
M3 = M1+M2
M3

array([[ 7, 12,  4],
       [ 1,  9, 13],
       [ 1, 11,  7],
       [13,  7,  7]], dtype=int8)

In [63]:
M1 + 10

array([[15, 14, 13],
       [11, 17, 18],
       [10, 12, 13],
       [17, 15, 11]], dtype=int8)

In [64]:
M1 + [2,3,1]

array([[ 7,  7,  4],
       [ 3, 10,  9],
       [ 2,  5,  4],
       [ 9,  8,  2]])

Subtraction

In [66]:
M1-M2

array([[ 3, -4,  2],
       [ 1,  5,  3],
       [-1, -7, -1],
       [ 1,  3, -5]], dtype=int8)

In [67]:
M2-M1

array([[-3,  4, -2],
       [-1, -5, -3],
       [ 1,  7,  1],
       [-1, -3,  5]], dtype=int8)

In [68]:
abs(M2-M1)

array([[3, 4, 2],
       [1, 5, 3],
       [1, 7, 1],
       [1, 3, 5]], dtype=int8)

In [69]:
M1 = np.array([[5,4,3], [1,7,8], [0,2,3],[7,5,1]], dtype = np.uint8)
M2 = np.array([[2,8,1], [0,2,5], [1,9,4],[6,2,6]], dtype = np.uint8)

In [70]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

In [71]:
M1-M2

array([[  3, 252,   2],
       [  1,   5,   3],
       [255, 249, 255],
       [  1,   3, 251]], dtype=uint8)

Scalar multiplication

In [73]:
M

array([[ 5,  4,  3],
       [ 1,  7, 56],
       [ 0,  2,  3],
       [ 7,  5,  1]], dtype=int8)

In [74]:
3*M

array([[ 15,  12,   9],
       [  3,  21, -88],
       [  0,   6,   9],
       [ 21,  15,   3]], dtype=int8)

In [75]:
3*(M1+M2)

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [76]:
3*M1 + 3* M2

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [77]:
(3+4)*M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [78]:
3*M1+4*M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [79]:
(3*4)*M1

array([[60, 48, 36],
       [12, 84, 96],
       [ 0, 24, 36],
       [84, 60, 12]], dtype=uint8)

In [80]:
3*(4*M1)

array([[60, 48, 36],
       [12, 84, 96],
       [ 0, 24, 36],
       [84, 60, 12]], dtype=uint8)

In [81]:
4*(3*M1)

array([[60, 48, 36],
       [12, 84, 96],
       [ 0, 24, 36],
       [84, 60, 12]], dtype=uint8)

In [82]:
(-3)*M1

array([[-15, -12,  -9],
       [ -3, -21, -24],
       [  0,  -6,  -9],
       [-21, -15,  -3]], dtype=int16)

In [83]:
-(3*M1)

array([[241, 244, 247],
       [253, 235, 232],
       [  0, 250, 247],
       [235, 241, 253]], dtype=uint8)

In [84]:
3*(-M1)

array([[241, 244, 247],
       [253, 235, 232],
       [  0, 250, 247],
       [235, 241, 253]], dtype=uint8)

In [85]:
-1 * M1

array([[-5, -4, -3],
       [-1, -7, -8],
       [ 0, -2, -3],
       [-7, -5, -1]], dtype=int16)

In [86]:
1*M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

<h5>Matrix Multiplication</h5>

In [88]:
M1 = np.array([[5,4,3], [1,7,8]], dtype = np.int8)
M2 = np.array([[2,8],[1,0],[2,5]], dtype = np.int8)

In [89]:
np.matmul(M1, M2)

array([[20, 55],
       [25, 48]], dtype=int8)

In [90]:
M1 @ M2

array([[20, 55],
       [25, 48]], dtype=int8)

In [91]:
M1 @ M2, M2 @ M1

(array([[20, 55],
        [25, 48]], dtype=int8),
 array([[18, 64, 70],
        [ 5,  4,  3],
        [15, 43, 46]], dtype=int8))

In [92]:
A=np.array([[1,2], [3,4]])
B=np.array([[5,6], [7,8]])
C=np.array([[3,8], [1,6]])

In [93]:
A @ (B@C), (A@B)@C

(array([[ 79, 284],
        [179, 644]]),
 array([[ 79, 284],
        [179, 644]]))

In [94]:
A@(B+C), A @ B + A @ C

(array([[24, 42],
        [56, 98]]),
 array([[24, 42],
        [56, 98]]))

In [95]:
(A + B) @C, A@C + B@C

(array([[ 26,  96],
        [ 42, 152]]),
 array([[ 26,  96],
        [ 42, 152]]))

<h5>Matrix Transpose</h5>

In [97]:
M

array([[ 5,  4,  3],
       [ 1,  7, 56],
       [ 0,  2,  3],
       [ 7,  5,  1]], dtype=int8)

In [98]:
np.transpose(M)

array([[ 5,  1,  0,  7],
       [ 4,  7,  2,  5],
       [ 3, 56,  3,  1]], dtype=int8)

In [99]:
M.reshape(3,4)

array([[ 5,  4,  3,  1],
       [ 7, 56,  0,  2],
       [ 3,  7,  5,  1]], dtype=int8)

In [100]:
M.T

array([[ 5,  1,  0,  7],
       [ 4,  7,  2,  5],
       [ 3, 56,  3,  1]], dtype=int8)

In [101]:
M, M.T.T

(array([[ 5,  4,  3],
        [ 1,  7, 56],
        [ 0,  2,  3],
        [ 7,  5,  1]], dtype=int8),
 array([[ 5,  4,  3],
        [ 1,  7, 56],
        [ 0,  2,  3],
        [ 7,  5,  1]], dtype=int8))

In [102]:
A.T +B.T, (A+B).T

(array([[ 6, 10],
        [ 8, 12]]),
 array([[ 6, 10],
        [ 8, 12]]))

In [103]:
(3 * M).T, 3*M.T

(array([[ 15,   3,   0,  21],
        [ 12,  21,   6,  15],
        [  9, -88,   9,   3]], dtype=int8),
 array([[ 15,   3,   0,  21],
        [ 12,  21,   6,  15],
        [  9, -88,   9,   3]], dtype=int8))

In [104]:
(A@B).T, B.T @ A.T

(array([[19, 43],
        [22, 50]]),
 array([[19, 43],
        [22, 50]]))

<h5>Read the size of matrix and then matrix values from user and print original matrix and its transpose</h5>

In [106]:
row = int(input("Enter number of rows: "))
col = int(input("Enter number of columns: "))
list1 =[]
for i in range(row*col):
        list1.append(int(input(f"Enter element {i}: ")))

A = np.array(list1)
B = A.reshape(row,col)

print("Original Matrix: \n", B)
C = B.T
print("Transpose: \n", C)

Enter number of rows:  1
Enter number of columns:  1
Enter element 0:  1


Original Matrix: 
 [[1]]
Transpose: 
 [[1]]


In [107]:
row = int(input("Enter number of rows: "))
col = int(input("Enter number of columns: "))
M0= np.zeros([row,col], dtype=np.int16)
for i in range(row):
    for j in range(col):
        num=int(input('enter value'))
        M0[i,j]= num
print("orignal matrix : \n", M0)
print("transpose matrix: \n", M0.T) 

Enter number of rows:  1
Enter number of columns:  1
enter value 1


orignal matrix : 
 [[1]]
transpose matrix: 
 [[1]]


In [108]:
M1 = np.array([[5,4,3], [1,7,8], [0,2,3],[7,5,1]], dtype = np.int8)
M2 = np.array([[2,8,1], [0,2,5], [1,9,4]], dtype = np.int8)

In [109]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [110]:
sum = 0
for i in range(M2.shape[0]):
    for j in range(M2.shape[1]):
        if i==j:
            sum+=M2[i][j]

print(sum)
        

8


In [111]:
add=0
for i in range (min(M1.shape)):
    add = M1[i,i] + add

In [112]:
add

15

In [113]:
add=0
for i in range (min(M2.shape)):
    add = M2[i,i] + add

In [114]:
add

8

In [115]:
M1.diagonal()

array([5, 7, 3], dtype=int8)

In [116]:
M2.diagonal()

array([2, 2, 4], dtype=int8)

In [117]:
M1.diagonal().sum()

15

In [118]:
M2.diagonal().sum()

8

In [119]:
M1.trace()

15

In [120]:
np.trace(M2)

8

In [121]:
np.trace(M1*3), 3*M1.trace()

(45, 45)

Determinant of matrix

In [123]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [124]:
np.linalg.det(M2)

-36.0

Inverse of matrix

In [126]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [127]:
np.linalg.inv(M2)

array([[ 1.02777778,  0.63888889, -1.05555556],
       [-0.13888889, -0.19444444,  0.27777778],
       [ 0.05555556,  0.27777778, -0.11111111]])

In [128]:
%precision 2
np.linalg.inv(M2)

array([[ 1.03,  0.64, -1.06],
       [-0.14, -0.19,  0.28],
       [ 0.06,  0.28, -0.11]])

Rank of matrix

In [130]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [131]:
np.linalg.matrix_rank(M1)

3

In [132]:
M3 = np.array([[1,2,3],[4,5,12],[2,7,6]])

In [133]:
M3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 2,  7,  6]])

In [134]:
np.linalg.matrix_rank(M3)

2

In [135]:
M4 = np.array([[1,2,3],[4,5,12],[2,4,6]])
M4

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 2,  4,  6]])

In [136]:
np.linalg.matrix_rank(M4)

2

In [137]:
M5 = np.array([[1,2,3],[4,8,12],[2,4,6]])
M5

array([[ 1,  2,  3],
       [ 4,  8, 12],
       [ 2,  4,  6]])

In [138]:
np.linalg.matrix_rank(M5)

1

In [139]:
M6 = np.array([[1,2],[1,3],[1,5],[1,7],[1,9]])
M6

array([[1, 2],
       [1, 3],
       [1, 5],
       [1, 7],
       [1, 9]])

In [140]:
np.linalg.matrix_rank(M6)

2

Types of matrices

In [142]:
R= np.array([[3,4,5],[1,3,8]])

In [143]:
R

array([[3, 4, 5],
       [1, 3, 8]])

In [144]:
R=R.reshape(1,-1)

In [145]:
R

array([[3, 4, 5, 1, 3, 8]])

Column matrix

In [147]:
C= np.array([[3,4,5],[1,3,8]])

In [148]:
C

array([[3, 4, 5],
       [1, 3, 8]])

In [149]:
C=C.reshape(-1,1)
C

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [150]:
C.shape

(6, 1)

In [151]:
C.T

array([[3, 4, 5, 1, 3, 8]])

In [152]:
R.T

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

Square matrix

In [154]:
S= np.array([[3,4,5],[1,3,8],[9,0,2]])
S

array([[3, 4, 5],
       [1, 3, 8],
       [9, 0, 2]])

In [155]:
def isSquareMatrix(M):
    if M.shape[0]==M.shape[1]:
        print("Square Matrix")
    else:
        print("Not a square matrix")

In [156]:
isSquareMatrix(S)

Square Matrix


In [157]:
S1= np.array([[3,4,5,5],[1,3,8,7],[9,0,2,1]])
S1

array([[3, 4, 5, 5],
       [1, 3, 8, 7],
       [9, 0, 2, 1]])

In [158]:
isSquareMatrix(S1)

Not a square matrix


In [159]:
def isRectangularMatrix(M):
    if M.shape[0]!=M.shape[1]:
        print(" Rectangular Matrix")
    else:
        print("Not a Rectangular matrix")

In [160]:
isRectangularMatrix(S1)

 Rectangular Matrix


In [161]:
isRectangularMatrix(S)

Not a Rectangular matrix


Diagonal matrix

In [163]:
np.random.randint(1,10)

5

Create a diagonal square matrix with n rows/colums
Read value of n from user

In [165]:
n = int(input("Enter no of row/cols: "))

M = np.zeros([n,n], dtype=np.int16)

for i in range(n):
    M[i,i]=np.random.randint(1,100)

M

Enter no of row/cols:  1


array([[50]], dtype=int16)

In [166]:
def isDiagonalMatrix(M):
    status = 1
    for i in range(M.shape[0]):
        if M[i].sum() == M[i][i]:
            continue
        else:
            status = 0
            break

    if status == 1:
        print("Diagonal Matrix")
    else:
        print("Not a diagonal matrix")
            
            

In [167]:
isDiagonalMatrix(S)

NameError: name 'isDiagonalMatrix' is not defined

In [ ]:
M

In [ ]:
isDiagonalMatrix(M)

In [ ]:
def isDiagonalMatrix(M):
    if (M>0).flatten().sum() == M.shape[0]:
        print("Diagonal")
    else:
        print("No")

In [ ]:
isDiagonalMatrix(S)

Identity matrix

In [ ]:
I= np.zeros([4,4], dtype=np.int16)

In [ ]:
I

In [ ]:
for i in range(I.shape[0]):
    I[i,i]= 1
I

In [ ]:
def isIdentityMatrix(M):
        if M.flatten().sum() == M.shape[0]:
            return True
        else:
            return False

In [ ]:
isIdentityMatrix(I)

Symmetric Matrix

In [ ]:
A = np.array([[1,2,3],[2,0,5],[3,5,6]])

In [ ]:
A

In [ ]:
A, A.T

In [ ]:
def issymmetricmatrix(M):
    # status =1
    # for i in range(M.shape[0]):
    #     for j in range(M.shape[1]):
    #         if M[i][j]==M[j][i]:
    #             continue
    #         else:
    #             status = 0
    #             break
    # if status == 1:
    #    return True
    # else:
    #     return False

    if (M == M.T).flatten().sum() == M.size:
        return True
    else:
        return False

In [ ]:
issymmetricmatrix(S)

Skew symmetric

In [ ]:
B = np.array([[0,3],[-3,0]])

In [ ]:
B

In [ ]:
-B, B.T

In [ ]:
-B == B.T

In [ ]:
def isskewsymmetric(M):
    if (-M == M.T).flatten().sum() == M.size:
        return True
    else:
        return False

In [ ]:
isskewsymmetric(B)

In [ ]:
isskewsymmetric(A)

Orthogonal Matrix

In [ ]:
I

In [ ]:
I.T

In [ ]:
np.linalg.inv(I)

In [ ]:
Rm = np.array([[np.cos(50), -np.sin(50)], [np.sin(50), np.cos(50)]])
Rm

In [ ]:
Rm.T

In [ ]:
np.linalg.inv(Rm)

In [215]:
P=np.array([[0,1,0],[1,0,0],[0,0,1]], dtype =np.int16)

In [217]:
P

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int16)

In [219]:
P.T

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int16)

In [221]:
np.linalg.inv(P)

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [223]:
np.linalg.det(P)

-1.00

In [ ]:
I

In [ ]:
H= np.array([[5,4,1,3],[8,9,0,3],[2,1,4,9],[7,3,1,4]])

In [ ]:
H

In [ ]:
H @ I

Eigenvalues and Eigenvectors

In [ ]:
A= np.array([[1,2],[3,4]], dtype = np.int8)

In [ ]:
value, vector = np.linalg.eig(A)

In [ ]:
value

In [ ]:
vector

In [ ]:
A @ vector

In [ ]:
value * vector

In [ ]:
A= np.array([[1,2,3,4],[3,4,5,6],[1,7,3,9],[8,7,3,5]], dtype = np.int8)

In [ ]:
A

In [ ]:
value, vector = np.linalg.eig(A)

In [ ]:
vector.dtype