1. Write a function to calculate the determinant of a square NumPy matrix.
2. Write a function to calculate the inverse of a square NumPy matrix.
3. Write a function to calculate the eigenvalues and eigenvectors of a square NumPy matrix.
4. Write a function to multiply two NumPy matrices.
5. Write a function to add two NumPy matrices.
6. Write a function to subtract two NumPy matrices.
7. Write  function to transpose a Numpy matrix.
8. Write a function to calculate the dot product of two numPy matrices.

In [2]:
import numpy as np

In [22]:
M = np.array([[11,22,33],[44,55,66],[77,88,99]])

In [24]:
M

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [26]:
def matrix_determinant(M):
    return np.linalg.det(M)

In [28]:
matrix_determinant(M)

3.961021986599773e-12

In [30]:
def matrix_inverse(M):
    return np.linalg.inv(M)

In [32]:
matrix_inverse(M)

array([[-9.16430157e+13,  1.83286031e+14, -9.16430157e+13],
       [ 1.83286031e+14, -3.66572063e+14,  1.83286031e+14],
       [-9.16430157e+13,  1.83286031e+14, -9.16430157e+13]])

In [44]:
def matrix_eigen(M):
    value, vector = np.linalg.eig(M)
    print(f"eigen value: {value}, \neigen vector: {vector}") 

In [46]:
matrix_eigen(M)

eigen value: [ 1.77285284e+02 -1.22852837e+01 -7.29482038e-15], 
eigen vector: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [48]:
a = np.array([[1,2],[11,22]])
b = np.array([[33,44],[7,8]])

In [50]:
def matrix_product(M1, M2):
    return M1@M2

In [52]:
matrix_product(a,b)

array([[ 47,  60],
       [517, 660]])

In [54]:
def matrix_addition(M1,M2):
    return M1+M2

In [56]:
matrix_addition(a,b)

array([[34, 46],
       [18, 30]])

In [58]:
def matrix_subtraction(M1,M2):
    return M1-M2

In [60]:
matrix_subtraction(a,b)

array([[-32, -42],
       [  4,  14]])

In [62]:
def matrix_transpose(M):
    return M.T

In [64]:
matrix_transpose(M)

array([[11, 44, 77],
       [22, 55, 88],
       [33, 66, 99]])

In [68]:
def matrix_dot_product(M1, M2):
    return np.dot(M1,M2)

In [70]:
matrix_dot_product(a,b)

array([[ 47,  60],
       [517, 660]])