<h3>Statement 1</h3>

Create two Numpy arrays, a and b, of the same size and filled with random values.
Then,perform the following operations on the arrays:
1. Add the two arrays together.
2. Substract the two arrays from each other.
3. Multiply the two arrays together.
4. Divide the two arrays by each other.
5. Take the dot product of the two arrays.

In [7]:
import numpy as np

In [9]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([23,24,25,26,27,28,29,30,31,32])

In [15]:
a, b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32]))

In [17]:
sum = a+b
sum

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41])

In [21]:
diff = b-a
diff

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [23]:
product = a*b
product

array([  0,  24,  50,  78, 108, 140, 174, 210, 248, 288])

In [31]:
div = a/b
div

array([0.        , 0.04166667, 0.08      , 0.11538462, 0.14814815,
       0.17857143, 0.20689655, 0.23333333, 0.25806452, 0.28125   ])

In [35]:
dotproduct = np.dot(a,b)
dotproduct

1320

<h3>Statement 2</h3>

Given a numpy array a, perform the following operations:
1. Find the mean, median and mode of the array.
2. Find the minimun and maximum values in the array.
3. Find the standard deviation of the array.
4. Normalize the array to have a mean of 0 and a standard deviation of 1.
5. Find the element-wise square root of the array.

In [62]:
import statistics as sts

In [64]:
a = np.array([45,64,76,12,36,38,91,72,33])

In [66]:
a.mean()

51.888888888888886

In [68]:
np.median(a)

45.0

In [70]:
sts.mode(a)

45

In [48]:
np.min(a)

12

In [50]:
np.max(a)

91

In [72]:
a.std()

23.811502563277852

In [80]:
a_standardized =(a - a.mean()) / a.std()
a_standardized

array([-0.28930929,  0.5086244 ,  1.01258251, -1.67519411, -0.66727788,
       -0.58328486,  1.64253016,  0.84459647, -0.79326741])

In [86]:
a_standardized.mean()

1.603655480014115e-16

In [88]:
a_standardized.std()

0.9999999999999999

In [90]:
np.sqrt(a)

array([6.70820393, 8.        , 8.71779789, 3.46410162, 6.        ,
       6.164414  , 9.53939201, 8.48528137, 5.74456265])

<h3>Statement 3</h3>

Given a numpy array a and a scalar value b, perform the following operations:
1. Add the scalar values to all elements of the array
2. Subtract the scalar value from all element of the array
3. Multiply all elements of the array by the scalar value
4. Divide all elements of the array by the scalar value
5. Raise all elements of the array to the power of the scalar value

In [94]:
a = np.array([12,17,19,37,63,77])

In [96]:
add = a+10
add

array([22, 27, 29, 47, 73, 87])

In [99]:
sub = a-10
sub

array([ 2,  7,  9, 27, 53, 67])

In [101]:
product = a*7
product

array([ 84, 119, 133, 259, 441, 539])

In [103]:
div = a/3
div

array([ 4.        ,  5.66666667,  6.33333333, 12.33333333, 21.        ,
       25.66666667])

In [105]:
pow = a**2
pow

array([ 144,  289,  361, 1369, 3969, 5929])