Bayes theorem

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df= pd.read_csv('Social_Network_Ads.csv')

In [8]:
df

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [10]:
# Separate the features and labels
x= df[['Age','EstimatedSalary']]
y=df['Purchased']

In [12]:
# import the class
from sklearn.naive_bayes import GaussianNB

In [18]:
# create the object
nb= GaussianNB()

In [20]:
# Apply the data / train the algorithm
nb.fit(x,y)

GaussianNB()

In [22]:
new = pd.DataFrame({
    'Age':[46,23,52],
    'EstimatedSalary':[67000,38700,140000]
})

In [24]:
new

Age  EstimatedSalary
0   46            67000
1   23            38700
2   52           140000

In [26]:
nb.predict_proba(new)

array([[0.48184269, 0.51815731],
       [0.98737899, 0.01262101],
       [0.00257448, 0.99742552]])

In [30]:
probs=nb.predict_proba(new)

In [32]:
probs.argmax(axis=1)

array([1, 0, 1], dtype=int64)

In [44]:
new1 = pd.DataFrame({
    'Age':[46,23,52,21,40,33],
    'EstimatedSalary':[67000,38700,140000,50000,370000,20000]
})

In [48]:
nb.predict_proba(new1)

array([[4.81842692e-01, 5.18157308e-01],
       [9.87378993e-01, 1.26210069e-02],
       [2.57448297e-03, 9.97425517e-01],
       [9.91148153e-01, 8.85184690e-03],
       [1.63060522e-25, 1.00000000e+00],
       [9.05563509e-01, 9.44364908e-02]])

In [50]:
probs=nb.predict_proba(new1)

In [52]:
probs.argmax(axis=1)

array([1, 0, 1, 0, 1, 0], dtype=int64)